#tomcat.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mywas
  template:
    metadata:
      labels:
        app: mywas
    spec:
      containers:
      - image: docker.io/maintndjs/was:1.4
        imagePullPolicy: Always
        name: mywas
        resources:
          limits:
            cpu: "0.5"
            memory: 1Gi
        ports:
        - containerPort: 8080
        env:
        - name: JAVA_OPTS
          value: "-Xms1024m -Xmx1024m"
