apiVersion: v2
appVersion: "3.5"
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 11.9.13
description: The Cloud-Native Ingress and API-management
home: https://konghq.com/
icon: https://s3.amazonaws.com/downloads.kong/universe/assets/icon-kong-inc-large.png
maintainers:
- email: bh7370608@naver.com
  name: somacksa
name: kong
sources:
- https://github.com/Kong/charts/tree/main/charts/kong
version: 2.33.3
